// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynshlwliftchzcshzmrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inluc2hsd2xpZnRjaHpjc2h6bXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjQ4MzcsImV4cCI6MjA3MjI0MDgzN30.2v-9Rz4NGycZo58mfNKz_wkLstc1zhrUs5rmj6KZI8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});